# Generated by Django 2.0.13 on 2019-07-29 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Start_date', models.DateTimeField(blank=True, null=True)),
                ('End_date', models.DateTimeField(blank=True, null=True)),
                ('Note', models.CharField(max_length=200)),
                ('Create', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Names', models.CharField(max_length=70)),
                ('Last_names', models.CharField(max_length=70)),
                ('Phone', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=200)),
                ('Reference', models.CharField(blank=True, max_length=200, null=True)),
                ('State', models.CharField(choices=[('inactive', 'Inactive'), ('check', 'Check'), ('active', 'Active'), ('complete', 'Complete')], default='check', max_length=10)),
                ('Description', models.CharField(max_length=200)),
                ('Note', models.CharField(max_length=200)),
                ('Create', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Names', models.CharField(max_length=70)),
                ('Last_names', models.CharField(max_length=70)),
                ('IdPersonal', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=200)),
                ('Start_Work', models.DateTimeField(blank=True, null=True)),
                ('State', models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active'), ('register', 'register')], default='check', max_length=10)),
                ('Create', models.DateTimeField(blank=True, null=True)),
                ('Note', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=200)),
                ('Note', models.CharField(max_length=200)),
                ('Create', models.DateTimeField(blank=True, null=True)),
                ('Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Descripcion', models.CharField(max_length=200)),
                ('Create', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Type'),
        ),
        migrations.AddField(
            model_name='job',
            name='Service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Service'),
        ),
    ]
