# Generated by Django 2.0.13 on 2019-08-17 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_auto_20190728_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Create', models.DateTimeField(blank=True, null=True)),
                ('Note', models.CharField(max_length=200)),
                ('State', models.CharField(choices=[('assing', 'assing'), ('active', 'Active')], default='assing', max_length=10)),
                ('Job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Job')),
                ('Profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Profile')),
            ],
        ),
    ]
