# Generated by Django 2.0.13 on 2019-08-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_assign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='Note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
