# Generated by Django 2.0.13 on 2019-08-26 00:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_auto_20190825_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 26, 0, 59, 19, 60661, tzinfo=utc), editable=False, null=True),
        ),
    ]
