# Generated by Django 2.0.13 on 2019-08-26 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_auto_20190825_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Create',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
