# Generated by Django 2.0.13 on 2019-08-26 01:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_auto_20190825_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 26, 1, 6, 31, 204722, tzinfo=utc), null=True),
        ),
    ]
