# Generated by Django 2.0.13 on 2019-08-26 01:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_auto_20190825_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Create',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
