# Generated by Django 2.0.13 on 2019-08-26 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0013_auto_20190825_1916'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('Order', 'Type')},
        ),
    ]
