# Generated by Django 2.0.13 on 2019-08-26 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0014_auto_20190825_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='State',
            field=models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active')], default='Active', max_length=10),
        ),
    ]
