# Generated by Django 2.0.13 on 2019-08-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0015_service_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
