# Generated by Django 2.0.13 on 2019-08-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0016_type_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='Name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
