# Generated by Django 2.0.13 on 2019-08-29 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0017_auto_20190828_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='Service',
        ),
        migrations.RemoveField(
            model_name='assign',
            name='Job',
        ),
        migrations.AddField(
            model_name='assign',
            name='End_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assign',
            name='Service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.Service'),
        ),
        migrations.AddField(
            model_name='assign',
            name='Start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
