# Generated by Django 2.0.13 on 2019-07-29 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
